### ISSUE TITLE
Further investigate why SA fails with soft-delete mixin

### ISSUE THREAD

**Issue by nZac** [level12/keg-elements#117]
- The tests seem to fail randomly, but upon further review they seem to fail on any fresh installation. By removing `recreate=false` in the tox configuration, the failures go away.

- The main issue is the `None type doesn't have __dict__`, the other two errors seem to be related or directly caused by that one.

- I was, at one point, able to get the tests to pass in 3.8 with minimal changes, but they then failed on 3.6... whack a mole. 

- By adding a simple delay to the test, it seemed to fix the issue, but then it popped back up again.

**Comment by guruofgentoo** [comment]
I believe the test(s) in question are currently skipped.
