### ISSUE TITLE
Drop Python 3.6 Support

### ISSUE THREAD

**Issue by calebsyring** [level12/keg-elements#155]
CI is failing: https://app.circleci.com/pipelines/github/level12/keg-elements?branch=127-description-fields.

We need to drop `py36` from `tox.ini` here:
https://github.com/level12/keg-elements/blob/f1cd4f8308b6edf7336302071fe7d87880500940/tox.ini#L2

**Comment by guruofgentoo** [comment]
FWIW, I am currently resolving CI issues on this lib.
