### ISSUE TITLE
Add a base class (or mixin) for working with forms

### ISSUE THREAD

**Issue by rsyring** [level12/keg-elements#166]
Example: https://github.com/level12/gb-h2r/blob/c78156c1b5891f6ee49b42b489e747ffa6a1de0e/how2recycle/libs/views.py#L175

Presumably, they created that as a mixin instead of a base class for the flexibility.  We might want to provide both, with the base class using the mixin.  If we do that, maybe we should do the same for the GridBase?

**Comment by rsyring** [comment]
@guruofgentoo you up for changing the FormMixin a bit with some of the changes I made here: https://github.com/level12/keg-elements/issues/166

* form_create() makes it easier to override just that functionality
* rename the "on" methods so they start with "form_" so that all form mixing functionality that isn't get/post have the same prefix.

**Comment by guruofgentoo** [comment]
Yep, I'll get that done here shortly.
