### ISSUE TITLE
SQLite job often fails in CI

### ISSUE THREAD

**Issue by calebsyring** [level12/keg-elements#176]
I ran into this today working on a separate issue and tried to track down the problem for too long to no avail. I saw a warning that had to do with SQLAlchemy not liking the `Numeric` column on `Thing` when using SQLite. I'm not sure if that has something to do with the failures or not.

**Comment by rsyring** [comment]
@calebsyring please get the exception out of a failed CI run and put it in this issue.  The CI jobs might not be available to reference when we get around to reviewing this problem.

**Comment by guruofgentoo** [comment]
FWIW, if this is still an issue, it's related to #117.
