### ISSUE TITLE
SentrySDK 2.0 breaks our Sentry integration

### ISSUE THREAD

**Issue by rsyring** [level12/keg-elements#196]
> TypeError: Unknown option 'with_locals'

https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#configuration-options

Should read through that doc and see what other 2.0 upgrades might be relevant.

https://github.com/level12/keg-elements/blob/99160e7b46408b4654da1893b27e1507e1b397f4/keg_elements/sentry.py#L247

Our exception handling is also broken:

https://github.com/level12/keg-elements/blob/99160e7b46408b4654da1893b27e1507e1b397f4/keg_elements/sentry.py#L409

`_compat.reraise()` no longer exists in their library.

**Comment by guruofgentoo** [comment]
Fixed in 0.12.0. `reraise` was moved to a `utils` module.
