### ISSUE TITLE
Form handling should check for form identification field

### ISSUE THREAD

**Issue by rsyring** [level12/keg-elements#3]
So you can have multiple forms on the same page and know which one got submitted.

**Comment by bchopson** [comment]
https://github.com/lepture/flask-wtf/issues/182#issuecomment-116590870

**Comment by bchopson** [comment]
Based on https://github.com/lepture/flask-wtf/issues/320#issuecomment-367748945, it sounds like the recommended approach for multiple forms is either having a different action per form, or using the "prefix" parameter from WTForms to differentiate form inputs. I considered providing a default prefix based on a form's `__name__`, but this would break a lot of tests in existing Keg projects.

**Comment by guruofgentoo** [comment]
I took a different approach to this. In many cases, I think having separate endpoints works well. I also think, though, that enforcing separate endpoints for forms is unnecessarily opinionated, and there may be cases for which one would want different form classes available on the same endpoint.

So, I'm adding a hidden field that will identify a "keg form". The name and value on that hidden field can be customized via class info. By default, forms will have it, but that can be disabled. Also, by default, the value will be validated by the form. The only place that should be a problem is for forms with custom rendering in templates, where the form ident field just isn't there. For backwards compatibility, those forms can turn off the ident field entirely, or just the validation portion.
