### ISSUE TITLE
Impossible to disable Cancel link

### ISSUE THREAD

**Issue by 3noch** [level12/keg-elements#41]
The current form template API does not provide any mechanism to disable the *Cancel* link. This is a problem because sometimes a form does not have a logical place to go after the user clicks *Cancel*. In such cases it would be better to simply not have a *Cancel* link. We already have several forms in production whose *Cancel* links take you back to the same form you were on before.

**Comment by rsyring** [comment]
IMO, this isn't a bug.  From a UI perspective, I'd always like to give the user a secondary option on the form.  In the cases where there is no place to go back to, have the cancel link go to the same page (which it sounds like it's already doing), but with a notice message, "Form submission canceled" or the like.

**Comment by 3noch** [comment]
Yeah, "bug" is too strong. I'll probably make a PR eventually to at least *allow* the user to disable the cancel button, perhaps by passing `none` explicitly as the `cancel_url`. Right now having two buttons that both end up at the same page is quite odd.

**Comment by 3noch** [comment]
I'm now confident that we want this feature. We are embedding a small form onto a larger page. The form is not the main feature of the page, so having a Cancel link is entirely confusing. Instead of hacking around the KegElements form rendered, I'd prefer to just support this when it's needed. A PR is coming.
