### ISSUE TITLE
`ValidateUnique` form validator can integrate better

### ISSUE THREAD

**Issue by 3noch** [level12/keg-elements#58]
Right now `ValidateUnique` requires that the Form have a `obj` member. This must be added manually to the form since it's not included by default on a WTForm form. However, WTForms do have a `_obj` member which has the same purpose. We could make `ValidateUnique` easier to use by utilizing this member.

**Comment by 3noch** [comment]
cc @bladams

**Comment by bladams** [comment]
It also appears that it is not possible to disable the existing object link without subclassing. https://github.com/level12/keg-elements/blob/master/keg_elements/forms/validators.py#L59
The attribute checked by `hasattr` is always set in the constructor. I think that should check `self.object_html_link is not None` instead

**Comment by bladams** [comment]
Also with out the 3rd argument using `getattr` here https://github.com/level12/keg-elements/blob/master/keg_elements/forms/validators.py#L51 serves no purpose over `self.obj`
