### ISSUE TITLE
form generation: smarter about handling foreign keys?

### ISSUE THREAD

**Issue by rsyring** [level12/keg-elements#8]
Would it be nice if the form generator recognized required foreign keys, like Payee.sales_rep_id and also set the coerce type to int to match?

**Comment by mtbrock** [comment]
There is a decent amount of progress on this issue. I think my aim was to allow forms to define relationships that would automatically get set up and rendered as select/multi-select fields. Looks like I moved a lot of stuff out of `forms/__init__.py` to `forms/form.py`.
