### ISSUE TITLE
form deprecation warning

### ISSUE THREAD

**Issue by guruofgentoo** [level12/keg-elements#88]
FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.

**Comment by calebsyring** [comment]
https://github.com/level12/keg-elements/commit/188f2d7ef274165a9b72503cefb8e5978c88ea08#diff-c0faf7a0afbb6bba39db5067bd0fb427

When I ran the tests locally on the master branch I no longer saw this warning.
