### ISSUE TITLE
pipenv usage is non-standard

### ISSUE THREAD

**Issue by rsyring** [level12/keg-elements#92]
@nZac is there a reason you pinned everything in this file? https://github.com/level12/keg-elements/blob/master/Pipfile

And why are you ignoring the lock file? https://github.com/level12/keg-elements/commit/c97dcc8c8fd6db27e00fcda25438cd33410d1ef0

Thanks.

**Comment by nZac** [comment]
https://github.com/level12/keg-elements/pull/103/commits/386faf267e07912dd1e3f2dcc9e932f89f41a6fc drops pipenv. Once it is merged this wont matter any more.
